// Code generated by go-swagger; DO NOT EDIT.

package engines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ory/keto/internal/httpclient/models"
)

// NewDoOryAccessControlPoliciesAllowedSubjectsParams creates a new DoOryAccessControlPoliciesAllowedSubjectsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDoOryAccessControlPoliciesAllowedSubjectsParams() *DoOryAccessControlPoliciesAllowedSubjectsParams {
	return &DoOryAccessControlPoliciesAllowedSubjectsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDoOryAccessControlPoliciesAllowedSubjectsParamsWithTimeout creates a new DoOryAccessControlPoliciesAllowedSubjectsParams object
// with the ability to set a timeout on a request.
func NewDoOryAccessControlPoliciesAllowedSubjectsParamsWithTimeout(timeout time.Duration) *DoOryAccessControlPoliciesAllowedSubjectsParams {
	return &DoOryAccessControlPoliciesAllowedSubjectsParams{
		timeout: timeout,
	}
}

// NewDoOryAccessControlPoliciesAllowedSubjectsParamsWithContext creates a new DoOryAccessControlPoliciesAllowedSubjectsParams object
// with the ability to set a context for a request.
func NewDoOryAccessControlPoliciesAllowedSubjectsParamsWithContext(ctx context.Context) *DoOryAccessControlPoliciesAllowedSubjectsParams {
	return &DoOryAccessControlPoliciesAllowedSubjectsParams{
		Context: ctx,
	}
}

// NewDoOryAccessControlPoliciesAllowedSubjectsParamsWithHTTPClient creates a new DoOryAccessControlPoliciesAllowedSubjectsParams object
// with the ability to set a custom HTTPClient for a request.
func NewDoOryAccessControlPoliciesAllowedSubjectsParamsWithHTTPClient(client *http.Client) *DoOryAccessControlPoliciesAllowedSubjectsParams {
	return &DoOryAccessControlPoliciesAllowedSubjectsParams{
		HTTPClient: client,
	}
}

/* DoOryAccessControlPoliciesAllowedSubjectsParams contains all the parameters to send to the API endpoint
   for the do ory access control policies allowed subjects operation.

   Typically these are written to a http.Request.
*/
type DoOryAccessControlPoliciesAllowedSubjectsParams struct {

	// Body.
	Body *models.OryAccessControlPolicyAllowedSubjectsInput

	/* Flavor.

	   The ORY Access Control Policy flavor. Can be "regex", "glob", and "exact".
	*/
	Flavor string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the do ory access control policies allowed subjects params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DoOryAccessControlPoliciesAllowedSubjectsParams) WithDefaults() *DoOryAccessControlPoliciesAllowedSubjectsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the do ory access control policies allowed subjects params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DoOryAccessControlPoliciesAllowedSubjectsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the do ory access control policies allowed subjects params
func (o *DoOryAccessControlPoliciesAllowedSubjectsParams) WithTimeout(timeout time.Duration) *DoOryAccessControlPoliciesAllowedSubjectsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the do ory access control policies allowed subjects params
func (o *DoOryAccessControlPoliciesAllowedSubjectsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the do ory access control policies allowed subjects params
func (o *DoOryAccessControlPoliciesAllowedSubjectsParams) WithContext(ctx context.Context) *DoOryAccessControlPoliciesAllowedSubjectsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the do ory access control policies allowed subjects params
func (o *DoOryAccessControlPoliciesAllowedSubjectsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the do ory access control policies allowed subjects params
func (o *DoOryAccessControlPoliciesAllowedSubjectsParams) WithHTTPClient(client *http.Client) *DoOryAccessControlPoliciesAllowedSubjectsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the do ory access control policies allowed subjects params
func (o *DoOryAccessControlPoliciesAllowedSubjectsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the do ory access control policies allowed subjects params
func (o *DoOryAccessControlPoliciesAllowedSubjectsParams) WithBody(body *models.OryAccessControlPolicyAllowedSubjectsInput) *DoOryAccessControlPoliciesAllowedSubjectsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the do ory access control policies allowed subjects params
func (o *DoOryAccessControlPoliciesAllowedSubjectsParams) SetBody(body *models.OryAccessControlPolicyAllowedSubjectsInput) {
	o.Body = body
}

// WithFlavor adds the flavor to the do ory access control policies allowed subjects params
func (o *DoOryAccessControlPoliciesAllowedSubjectsParams) WithFlavor(flavor string) *DoOryAccessControlPoliciesAllowedSubjectsParams {
	o.SetFlavor(flavor)
	return o
}

// SetFlavor adds the flavor to the do ory access control policies allowed subjects params
func (o *DoOryAccessControlPoliciesAllowedSubjectsParams) SetFlavor(flavor string) {
	o.Flavor = flavor
}

// WriteToRequest writes these params to a swagger request
func (o *DoOryAccessControlPoliciesAllowedSubjectsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param flavor
	if err := r.SetPathParam("flavor", o.Flavor); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
