// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OryAccessControlPolicyAllowedSubjectsInput Input for getting a list of subjects that are allowed to do an action.
//
// swagger:model oryAccessControlPolicyAllowedSubjectsInput
type OryAccessControlPolicyAllowedSubjectsInput struct {

	// Action is the action that is requested on the resource.
	Action string `json:"action,omitempty"`

	// Context is the request's environmental context.
	Context interface{} `json:"context,omitempty"`

	// Resource is the resource that access is requested to.
	Resource string `json:"resource,omitempty"`
}

// Validate validates this ory access control policy allowed subjects input
func (m *OryAccessControlPolicyAllowedSubjectsInput) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this ory access control policy allowed subjects input based on context it is used
func (m *OryAccessControlPolicyAllowedSubjectsInput) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OryAccessControlPolicyAllowedSubjectsInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OryAccessControlPolicyAllowedSubjectsInput) UnmarshalBinary(b []byte) error {
	var res OryAccessControlPolicyAllowedSubjectsInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
